import {
  VITE_GRAPHQL_URL,
  VITE_GRAPHQL_INTERNAL_URL,
  VITE_GRAPHQL_WS_URL,
  VITE_OIDC_ISSUER,
  VITE_OIDC_CLIENT_ID,
  VITE_OIDC_CLIENT_SECRET,
  VITE_OIDC_POST_LOGOUT_REDIRECT_URI,
  VITE_OIDC_TOKEN_REFRESH_MAX_RETRIES,
  VITE_OIDC_CLIENT_SCOPE,
  VITE_OIDC_REDIRECT_URI,
  VITE_REFRESH_TOKEN_ENDPOINT,
  VITE_REFRESH_PAGE_ON_SESSION_TIMEOUT,
} from "./env";

export const config = {
  oidc: {
    issuer: VITE_OIDC_ISSUER,
    clientId: VITE_OIDC_CLIENT_ID,
    clientSecret: VITE_OIDC_CLIENT_SECRET,
    postLogoutRedirectUri: VITE_OIDC_POST_LOGOUT_REDIRECT_URI,
    redirectUri: VITE_OIDC_REDIRECT_URI,
    refreshPageOnSessionTimeout: VITE_REFRESH_PAGE_ON_SESSION_TIMEOUT,
    refreshTokenEndpoint: VITE_REFRESH_TOKEN_ENDPOINT,
    refreshTokenMaxRetries: VITE_OIDC_TOKEN_REFRESH_MAX_RETRIES,
    scope: VITE_OIDC_CLIENT_SCOPE,
  },
  graphql: {
    http: VITE_GRAPHQL_URL,
    httpInternal: VITE_GRAPHQL_INTERNAL_URL,
    ws: VITE_GRAPHQL_WS_URL,
  },
};
